<template>
 <div class="spinner-container">
<div class="loadingio-spinner-bean-eater-5syuz3bisyh"><div class="ldio-jagnk7mimyj">
<div><div></div><div></div><div></div></div><div><div></div><div></div><div></div></div>
</div></div>
  </div>
</template> 

<style scoped>
.spinner-container {
  width: 100%;
  height: 100%;
  display: flex;
  justify-content: center;
  align-items: center;
}
@keyframes ldio-jagnk7mimyj-1 {
    0% { transform: rotate(0deg) }
   50% { transform: rotate(-45deg) }
  100% { transform: rotate(0deg) }
}
@keyframes ldio-jagnk7mimyj-2 {
    0% { transform: rotate(180deg) }
   50% { transform: rotate(225deg) }
  100% { transform: rotate(180deg) }
}
.ldio-jagnk7mimyj > div:nth-child(2) {
  transform: translate(-15px,0);
}
.ldio-jagnk7mimyj > div:nth-child(2) div {
  position: absolute;
  top: 20px;
  left: 20px;
  width: 60px;
  height: 30px;
  border-radius: 60px 60px 0 0;
  background: #f8b26a;
  animation: ldio-jagnk7mimyj-1 1s linear infinite;
  transform-origin: 30px 30px
}
.ldio-jagnk7mimyj > div:nth-child(2) div:nth-child(2) {
  animation: ldio-jagnk7mimyj-2 1s linear infinite
}
.ldio-jagnk7mimyj > div:nth-child(2) div:nth-child(3) {
  transform: rotate(-90deg);
  animation: none;
}@keyframes ldio-jagnk7mimyj-3 {
    0% { transform: translate(95px,0); opacity: 0 }
   20% { opacity: 1 }
  100% { transform: translate(35px,0); opacity: 1 }
}
.ldio-jagnk7mimyj > div:nth-child(1) {
  display: block;
}
.ldio-jagnk7mimyj > div:nth-child(1) div {
  position: absolute;
  top: 46px;
  left: -4px;
  width: 8px;
  height: 8px;
  border-radius: 50%;
  background: #e15b64;
  animation: ldio-jagnk7mimyj-3 1s linear infinite
}
.ldio-jagnk7mimyj > div:nth-child(1) div:nth-child(1) { animation-delay: -0.67s }
.ldio-jagnk7mimyj > div:nth-child(1) div:nth-child(2) { animation-delay: -0.33s }
.ldio-jagnk7mimyj > div:nth-child(1) div:nth-child(3) { animation-delay: 0s }
.loadingio-spinner-bean-eater-5syuz3bisyh {
  width: 40px;
  height: 40px;
  display: inline-block;
  overflow: hidden;
  background: none;
}
.ldio-jagnk7mimyj {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(0.4);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-jagnk7mimyj div { box-sizing: content-box; }
/* generated by https://loading.io/ */
</style>